# Generated by Django 4.2.4 on 2023-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('custom', 'Custom')], max_length=10)),
                ('food_consumption_percentage', models.PositiveIntegerField()),
                ('food_consumption_daily_unit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
