# Generated by Django 4.2.4 on 2023-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
