# Generated by Django 4.2.4 on 2023-08-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0003_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crops_optimizer.needscategory'),
            preserve_default=False,
        ),
    ]
