# Generated by Django 4.2.4 on 2023-08-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0005_resourcecat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedsCategory',
            new_name='NeedCat',
        ),
    ]
