# Generated by Django 4.2.4 on 2023-08-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0006_rename_needscategory_needcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='needs', to='crops_optimizer.needcat'),
        ),
        migrations.AlterField(
            model_name='resourcecat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='crops_optimizer.resourcecat')),
            ],
        ),
    ]
