# Generated by Django 4.2.4 on 2023-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0007_alter_need_category_alter_resourcecat_name_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatStructCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_cat',
            new_name='category',
        ),
    ]
