# Generated by Django 4.2.4 on 2023-08-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0009_natstruct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natstruct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nat_structs', to='crops_optimizer.natstructcat'),
        ),
        migrations.AlterField(
            model_name='natstruct',
            name='days_between_harvest',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='natstruct',
            name='resource_cut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut_nat_structs', to='crops_optimizer.resource'),
        ),
        migrations.AlterField(
            model_name='natstruct',
            name='resource_cut_yield',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='natstruct',
            name='resource_harvest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_nat_structs', to='crops_optimizer.resource'),
        ),
        migrations.AlterField(
            model_name='natstruct',
            name='resource_harvest_yield',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
