# Generated by Django 4.2.4 on 2023-08-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0010_alter_natstruct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natstruct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nat_structs', to='crops_optimizer.natstructcat'),
            preserve_default=False,
        ),
    ]
