# Generated by Django 4.2.4 on 2023-08-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops_optimizer', '0011_alter_natstruct_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NatStruct',
        ),
    ]
